### ISSUE TITLE
Need to Help urgently 

### ISSUE THREAD

**Issue by Palash-Mandal** [Anubhavjain786/grapesjs-accordion#1]
How to add get the module dynamic id before each CSS class to **encapsulate** the CSS for 

![image](https://user-images.githubusercontent.com/17553816/158590753-9a537134-8016-4a37-aec0-05de213ab6a9.png)

I need that dynamic ID before each CSS Class while drop the component 

as per my screenshot CSS structure will be like 

#ij7j .accordion__group{
  margin-bottom:16px;
}

#ij7j  .accordion__button{
  background-color:rgb(168, 168, 168);
  padding-top:16px;
  padding-right:16px;
  padding-bottom:16px;
  padding-left:16px;
  width:100%;
  text-align:left;
  border-top-width:initial;
  border-right-width:initial;
  border-bottom-width:initial;
  border-left-width:initial;
  border-top-style:none;
  border-right-style:none;
  border-bottom-style:none;
  border-left-style:none;
  border-top-color:initial;
  border-right-color:initial;
  border-bottom-color:initial;
  border-left-color:initial;
  border-image-source:initial;
  border-image-slice:initial;
  border-image-width:initial;
  border-image-outset:initial;
  border-image-repeat:initial;
  outline-color:initial;
  outline-style:none;
  outline-width:initial;
  cursor:pointer;
  display:flex;
  align-items:flex-start;
  border-top-left-radius:8px;
  border-top-right-radius:8px;
  border-bottom-right-radius:8px;
  border-bottom-left-radius:8px;
  transition-duration:0.2s;
  transition-timing-function:cubic-bezier(0.175, 0.885, 0.32, 1.275);
  transition-delay:0s;
  transition-property:all;
}

Please help

![image](https://user-images.githubusercontent.com/17553816/158591323-75ce198b-872f-4644-a9ee-cff7691ed158.png)

**Comment by Anubhavjain786** [comment]
You can set custom ID to component: https://grapesjs.com/docs/api/component.html#component
